- utils.py
파이프라인에 필요한 모듈들을 추가하였습니다.
1. data_split : train, test 나누는 모델
3. labeling : 피처 중에서 object 타입인 컬럼들의 경우 라벨인코딩(unseen데이터 처리 포함)
4. model_predict :  예측하는 모듈
5. model_scoring : 평가하는 모듈
6. model_save : 모델 저장
3. labeling 
- unseen 데이터 처리되도록 labeling 함수를 만들었고 실제 데이터가 추가됐을 경우에 확인이 필요함
확인되면 20번 이슈는 종료하겠습니다~
close #20
> <feat> : add modules

- errors/app_exceptions.py
- errors/handlers.py
- main.py
- routers/redisai.py
- schemas/request.py
- schemas/response.py
- utils.py
예외 처리 정의와 응답 모델 작성
close #38
loguru가 없다면
pip install loguru 먼저 실행! 
🖥1. 코드 설명
main.py
```
@router.post("/income/predict",response_model=Item)
def predict_income(item: IncomeBody, name : str, model_key : str):
if not client.exists("model"):
load_model(client,"model",name)
result = predict(client, f"{model_key}", item)
item.target = handle_result(result)
if item.target == 1:
item.context = "소득이 10만달러 이상"
else:
item.context = "소득이 10만달러 미만"
return item
```
handle_result를 통해 예측 처리~~
schemas/request.py
```
class IncomeBody(BaseModel):
age : int
workclass : int
fnlwgt : int
education : int
education_num : int
marital_status : int
occupation : int
relationship : int
race : int
sex : int
capital_gain : int
capital_loss: int
hours_per_week : int
native_country : int
target : Optional[int] = None …
```
> <feat> add exception definition

- routers/income.py
- service/app_service.py
- load_model 하는 부분에서 에러가 발생됩니다.
함께 답을 찾아봅시다~
>
> <feat> code refactoring_errors

- db/database.py
- main.py
- routers/income.py
- service/app_service.py
- utils/handlers.py
- utils/service_result.py
비즈니스 레이어와 컨트롤러 레이어를 리팩토링했습니다~!
레이어 구조를 변환
더 좋게 리팩토링할 아이디어 있으면 언제든지 지적해주세요
close #40
> <refactor> refactoring spilt service

- routers/income.py
- utils/app_exceptions.py
- utils/request_exceptions.py
우리가 정의한 에러문에 맞추어 내장된 에러 메세지를 변경하였습니다.
입력값 오류가 나올때 
{
"detail": [
{
"loc": [
"string",
0
],
"msg": "string",
"type": "string"
}
]
}
위 타입에서 아래의 타입으로 변경하였습니다.
{
"exception": "value_error.jsondecode",
"context": "입력 값 오류입니다. 입력값을 확인하세요."
}
> <feat> change exception type

- .env
- config.py
- db/database.py
- routers/income.py
- config 파일을를 추가하였습니다.
- 다만 config.py에서 Settings.Config 통해서 .env 에 정의할 경우에 에러가 발생합니다.
#56
> <feat> add config

- main.py
- routers/income.py
- schemas/response.py
- service/app_service.py
data 폴더 삭제, minio 삭제, pre-commit 설정
> <chore> new error & code cleanup

- app/main.py
- app/routers/income.py
- db의 경로가 app 과 동일경로에 있어서 절대경로 인식하도록 코드 수정하였습니다.
- uvicorn 실행에 번거로운 부분이 있어서 main.py 에 run 추가하였습니다.
close #70
> <chore> fix path error

- app/routers/income.py
- app/service/app_service.py
- app/utils/handlers.py
- app/utils/service_result.py
- main.py
- main.py의 위치가 app 안쪽에 있어서 상위경로로 옮겼습니다.
- 추가로 main의 위치변경에 따라서 변동되는 경로도 함께 수정 완료했습니다.
close #70
> <chore> fix path error2

- .env
- config.py
> <feat> add environment variable

- app/service/app_service.py
prodcution : 모델을 학습할 때 params, metrics 들을 db, Minio 에 저장합니다.
predict : mlflow에 Production 모델을 불러옵니다
기존 joblib함수를 이용하는 부분을 mlflow 를 이용하여 연동을 하였습니다.
> <feat> add mlflow production/predict

- coin/data_verification.py
크롤링해서 온 코인데이터의 null 값 및 4시간 간격으로 잘 받아와지나를 확인하는 코드입니다.
연속된 날짜와 DB의 날짜를 비교하여 누락된 날짜가 있는지 없는지 확인하는 코드입니다.
```
def coin_date_check(datetime_list):
datetime = []
for i in range(len(datetime_list)):
datetime.append(datetime_list[i].date())
unique_date_list = np.unique(datetime)
date_idx = pd.date_range(datetime_list[0].date(), datetime_list[-1].date())
no_data_idx = []
if len(date_idx) != len(unique_date_list):
print("결측 date 존재")
for i in range(len(date_idx)):
if date_idx[i].date() in unique_date_list:
pass
else:
no_data_idx.append(i)
return no_data_idx
```
시간 간격이 4시간인지 아닌지 확인하는 코드입니다.
np.unique를 한 이유는 중복된 데이터가 있기 때문입니다.
```
def coin_time_check(datetime_list):
datetime_list = np.unique(datetime_list)
for i in range(len(datetime_list) - 1):
if (datetime_list[i + 1] - datetime_list[i]).seconds / …
```
> <feat> check data

- coin/.env
- coin/coin_predict.py
- coin/coin_service.py
- coin/config.py
- coin/data_collection.py
- coin/data_verification.py
- dags/coinflow.py
- 기존 코인 데이터 수집하여 model을  train 후 model과 metrics를 mlflow로 관리할 수 있도록
적용하였습니다.
- airflow db를 postgresql 로 수정완료됐습니다.
- 현재 airflow로 데이터 수집, 모델훈련 모두 정상적으로 진행됩니다.
데이터검증하는 함수 완성된 후 추가하면 파이프라인은 완성될듯합니다.
> <feat> apply mlflow_coin

- coin/coin_service.py
- coin/data_collection.py
- coin/data_verification.py
DB에 접근하여 데이터 검증하는 기능 구현
coin/coin_service.py
```
def get_ohlcv(self, ticker, interval):
"""
작성자 : 이대형
코인 전체데이터 가져오기
"""
print(f"{ticker} get total ohlcv.....")
try:
dfs = []
df = pyupbit.get_ohlcv(ticker, interval=interval)
dfs.append(df)
while len(df) >= 200:
try:
df = pyupbit.get_ohlcv(ticker, interval=interval, to=df.index[0])
dfs.append(df)
time.sleep(0.2)
except Exception:
pass
df = pd.concat(dfs)
df = df.sort_index()
df.drop_duplicates(inplace=True).  # 중복 데이터를 지우기 위해 추가
return df
except Exception:
pass
```
coin/data_verification.py
```
cursor.execute(f"""SELECT * FROM public."{settings.ticker}" order by index;""")
conn.commit()
cursor.execute(
f"""DELETE FROM public."{settings.ticker}" WHERE ctid IN
(SELECT A.ctid FROM (SELECT ctid, ROW_NUMBER() over
(PARTITION BY index ORDER BY …
```
> <feat> data collection and verification

- coin/coin_predict.py
- coin/coin_service.py
- train 함수에서 y_pred 부분을 가져올 때 리스케일링 된 값을
받아오다보니, metrics 값이 부정확함. 스케일링 된 pred를 받도록 수정함
> <refactor> coin_predict refactoring

- coin/data_verification.py
연산을 고려하여 for문을 줄였습니다.
하지만 DB 자체의 데이터를 변경하는 것이 아닌 DataFrame으로 데이터를 처리하는 코드입니다.
DB의 데이터를 직접 수정하는 코드를 짜보겠습니다.
> Check data

- .pre-commit-config.yaml
- app/routers/income.py
- coin/coin_predict.py
mlflow에 coin scaler를 불러올 수 있는 함수를 추가하였습니다.
모델을 저장하는 방법과 같은 방식을 이용하여 작성하였습니다.
> <feat> add mlflow coin scaler, scaler_y

- .github/workflows/cicd.yml
> <test> git action test

- docker-compose.yaml
docker-compose mlflow의 커맨드를 수정하였습니다!
> <fix> fix docker-compose mlflow command

- .pre-commit-config.yaml
- app/routers/income.py
- app/schemas/request.py
- app/schemas/response.py
- 코인 데이터 수집과 딥러닝 모델 만든 이후에
실질적으로 사용할 수 있도록 api 에 기능 추가하였습니다.
close #114
> <feat> add coin_predict
